# CREACION FK MODELO DE LLAMADAS
USE ODS;

 
ALTER TABLE ODS_HC_LLAMADAS MODIFY COLUMN ID_DEPARTAMENTO_CC INT(10);
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_lla_dep_idx (ID_DEPARTAMENTO_CC ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_lla_dep FOREIGN KEY(ID_DEPARTAMENTO_CC)
   REFERENCES ODS_DM_DEPARTAMENTOS_CC(ID_DEPARTAMENTO_CC);
   
ALTER TABLE ODS_HC_LLAMADAS MODIFY COLUMN ID_AGENTE_CC INT(10);
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_lla_age_idx (ID_AGENTE_CC ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_lla_age FOREIGN KEY(ID_AGENTE_CC)
   REFERENCES ODS_DM_AGENTES_CC(ID_AGENTE_CC);
   
ALTER TABLE ODS_HC_LLAMADAS MODIFY COLUMN ID_FLG_TRANSFERIDO INT(10);
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_lla_transf_idx (ID_FLG_TRANSFERIDO ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_lla_transf FOREIGN KEY(ID_FLG_TRANSFERIDO)
   REFERENCES ODS_DM_FLG_TRANSFER(ID_FLG_TRANSFERIDO);
   

