# CREACION FK MODELO DE FACTURAS

USE ODS;
 

ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_cli FOREIGN KEY(ID_CLIENTE)
   REFERENCES ODS_HC_CLIENTES(ID_CLIENTE);
   
ALTER TABLE ODS_HC_FACTURAS MODIFY COLUMN ID_METODO_PAGO INT(10);
ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_met_idx (ID_METODO_PAGO ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_met FOREIGN KEY(ID_METODO_PAGO)
   REFERENCES ODS_DM_METODOS_PAGO(ID_METODO_PAGO);

   
ALTER TABLE ODS_HC_FACTURAS MODIFY COLUMN ID_CICLO_FACTURACION INT(10);
ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_cic_idx (ID_CICLO_FACTURACION ASC);
ALTER TABLE ODS.ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_cic_dir FOREIGN KEY(ID_CICLO_FACTURACION)
   REFERENCES ODS_DM_CICLOS_FACTURACION(ID_CICLO_FACTURACION);

   
