# POBLAMOS TABLAS DE MODELO DE LLAMADAS
USE ODS;

INSERT INTO ODS.ODS_DM_AGENTES_CC VALUES (-98,'NO APLICA', NOW(), NOW());
INSERT INTO ODS.ODS_DM_AGENTES_CC VALUES (-99,'DESCONOCIDO', NOW(), NOW());
COMMIT;
ANALYZE TABLE ODS_DM_AGENTES_CC;

INSERT INTO ODS_DM_FLG_TRANSFER VALUES (-98,'NO APLICA', NOW(), NOW());
INSERT INTO ODS.ODS_DM_FLG_TRANSFER VALUES (-99,'DESCONOCIDO', NOW(), NOW());
COMMIT;
ANALYZE TABLE ODS_DM_FLG_TRANSFER;

INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (-98,'NO APLICA', NOW(), NOW());
INSERT INTO ODS.ODS_DM_DEPARTAMENTOS_CC VALUES (-99,'DESCONOCIDO', NOW(), NOW());
COMMIT;
ANALYZE TABLE ODS_DM_DEPARTAMENTOS_CC;


# Actualización periódica de las tablas

INSERT INTO ODS.ODS_DM_AGENTES_CC (DE_AGENTE_CC
, FC_INSERT
, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(STAGE.STG_CONTACTOS_IVR.AGENT)), NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR
LEFT OUTER JOIN ODS.ODS_DM_AGENTES_CC
	 ON UPPER(TRIM(STAGE.STG_CONTACTOS_IVR.AGENT)) = 
        UPPER(TRIM(ODS.ODS_DM_AGENTES_CC.DE_AGENTE_CC))
WHERE LENGTH (TRIM(STAGE.STG_CONTACTOS_IVR.AGENT))<>0
AND ODS.ODS_DM_AGENTES_CC.DE_AGENTE_CC IS NULL;
COMMIT;

INSERT INTO ODS.ODS_DM_FLG_TRANSFER (DE_FLG_TRANSFERIDO
, FC_INSERT
, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(STAGE.STG_CONTACTOS_IVR.FLG_TRANSFER)), NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR
LEFT OUTER JOIN ODS.ODS_DM_FLG_TRANSFER
	 ON UPPER(TRIM(STAGE.STG_CONTACTOS_IVR.FLG_TRANSFER)) = 
        UPPER(TRIM(ODS.ODS_DM_FLG_TRANSFER.DE_FLG_TRANSFERIDO))
WHERE LENGTH (TRIM(STAGE.STG_CONTACTOS_IVR.FLG_TRANSFER))<>0
AND ODS.ODS_DM_FLG_TRANSFER.DE_FLG_TRANSFERIDO IS NULL;
COMMIT;

INSERT INTO ODS.ODS_DM_DEPARTAMENTOS_CC (DE_DEPARTAMENTO_CC
, FC_INSERT
, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(STAGE.STG_CONTACTOS_IVR.SERVICE)), NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR
LEFT OUTER JOIN ODS.ODS_DM_DEPARTAMENTOS_CC
	 ON UPPER(TRIM(STAGE.STG_CONTACTOS_IVR.SERVICE)) = 
        UPPER(TRIM(ODS.ODS_DM_DEPARTAMENTOS_CC.DE_DEPARTAMENTO_CC))
WHERE LENGTH (TRIM(STAGE.STG_CONTACTOS_IVR.SERVICE))<>0
AND ODS.ODS_DM_DEPARTAMENTOS_CC.DE_DEPARTAMENTO_CC IS NULL;
COMMIT;


INSERT INTO ODS.ODS_HC_LLAMADAS (ID_IVR 
, TELEFONO_LLAMADA
, FC_INICIO_LLAMADA
, FC_FIN_LLAMADA
, ID_DEPARTAMENTO_CC
, ID_FLG_TRANSFERIDO
, ID_AGENTE_CC
, FC_INSERT
, FC_MODIFICACION)
SELECT CON.ID
, CASE WHEN LENGTH(TRIM(CON.PHONE_NUMBER))<>0 
			THEN CON.PHONE_NUMBER ELSE 999999999 END AS TELEFONO_LLAMADA
, CASE WHEN LENGTH(TRIM(CON.START_DATETIME))<>0 
			THEN STR_TO_DATE(DATE_FORMAT(CON.START_DATETIME,'%d/%m/%Y'),'%d/%m/%Y')
			ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END AS FC_INICIO_LLAMADA
, CASE WHEN LENGTH(TRIM(CON.END_DATETIME))<>0
		    THEN STR_TO_DATE(DATE_FORMAT(CON.END_DATETIME,'%d/%m/%Y'),'%d/%m/%Y')
            ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END AS FC_FIN_LLAMADA
, DEP.ID_DEPARTAMENTO_CC
, TRANS.ID_FLG_TRANSFERIDO
, AGENT.ID_AGENTE_CC
, NOW()
, NOW()

FROM STAGE.STG_CONTACTOS_IVR AS CON
	 INNER JOIN ODS.ODS_DM_DEPARTAMENTOS_CC AS DEP
				ON CASE WHEN LENGTH(TRIM(CON.SERVICE))<>0 THEN UPPER(TRIM(CON.SERVICE))
                ELSE 'DESCONOCIDO' END = DEP.DE_DEPARTAMENTO_CC
	 INNER JOIN ODS.ODS_DM_FLG_TRANSFER AS TRANS
                ON CASE WHEN LENGTH(TRIM(CON.FLG_TRANSFER))<>0
                THEN UPPER(TRIM(CON.FLG_TRANSFER))
                ELSE 'DESCONOCIDO' END = TRANS.DE_FLG_TRANSFERIDO
	 INNER JOIN ODS.ODS_DM_AGENTES_CC AS AGENT
                ON CASE WHEN LENGTH(TRIM(CON.AGENT))<>0
                THEN UPPER(TRIM(CON.AGENT)) 
				ELSE 'DESCONOCIDO' END = AGENT.DE_AGENTE_CC;
COMMIT;
ANALYZE TABLE ODS.ODS_HC_LLAMADAS;

                




