SELECT 'ODS_DM_AGENTES_CC' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_AGENTES_CC
UNION ALL
SELECT 'ODS.ODS_DM_CICLOS_FACTURACION' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_CICLOS_FACTURACION
UNION ALL
SELECT 'ODS.ODS_DM_METODOS_PAGO' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_METODOS_PAGO
UNION ALL
SELECT 'ODS.ODS_DM_CANALES' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_CANALES
UNION ALL
SELECT 'ODS.ODS_DM_CIUDADES_ESTADOS' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_CIUDADES_ESTADOS
UNION ALL
SELECT 'ODS.ODS_DM_COMPANYAS' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_COMPANYAS
UNION ALL
SELECT 'ODS.ODS_DM_FLG_TRANSFER' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_FLG_TRANSFER
UNION ALL
SELECT 'ODS.ODS_DM_PAISES' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_PAISES
UNION ALL
SELECT 'ODS.ODS_DM_PRODUCTOS' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_PRODUCTOS
UNION ALL
SELECT 'ODS.ODS_DM_PROFESIONES' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_PROFESIONES
UNION ALL
SELECT 'ODS.ODS_DM_DEPARTAMENTOS_CC' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_DEPARTAMENTOS_CC
UNION ALL
SELECT 'ODS.ODS_DM_SEXOS' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_DM_SEXOS
UNION ALL
SELECT 'ODS.ODS_HC_CLIENTES' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_HC_CLIENTES
UNION ALL
SELECT 'ODS.ODS_HC_LLAMADAS' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_HC_LLAMADAS
UNION ALL
SELECT 'ODS.ODS_HC_DIRECCIONES' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_HC_DIRECCIONES
UNION ALL
SELECT 'ODS.ODS_HC_FACTURAS' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_HC_FACTURAS
UNION ALL
SELECT 'ODS.ODS_HC_SERVICIOS' AS TABLA, COUNT(*) AS NUM_REGISTROS FROM ODS.ODS_HC_SERVICIOS
