USE STAGE;
SELECT COUNT(*) AS TOTAL_REGITROS 
, SUM(CASE WHEN LENGTH(TRIM(BILL_REF_NO)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_BILL_REF_NO
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(BILL_REF_NO)) <> 0 THEN BILL_REF_NO ELSE 0 END) AS TOTAL_BILL_REF_NO_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(CUSTOMER_ID)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_CUSTOMER_ID
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(CUSTOMER_ID)) <> 0 THEN CUSTOMER_ID ELSE 0 END) AS TOTAL_CUSTOMER_ID_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(START_DATE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_START_DATE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(START_DATE)) <> 0 THEN START_DATE ELSE 0 END) AS TOTAL_START_DATE_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(END_DATE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_END_DATE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(END_DATE)) <> 0 THEN END_DATE ELSE 0 END) AS TOTAL_END_DATE_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(STATEMENT_DATE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_STATEMENT_DATE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(STATEMENT_DATE)) <> 0 THEN STATEMENT_DATE ELSE 0 END) AS TOTAL_STATEMENT_DATE_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(PAYMENT_DATE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_PAYMENT_DATE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PAYMENT_DATE)) <> 0 THEN PAYMENT_DATE ELSE 0 END) AS TOTAL_PAYMENT_DATE_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(BILL_CYCLE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_BILL_CYCLE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(BILL_CYCLE)) <> 0 THEN BILL_CYCLE ELSE 0 END) AS TOTAL_BILL_CYCLE_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(AMOUNT)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_AMOUNT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AMOUNT)) <> 0 THEN AMOUNT ELSE 0 END) AS TOTAL_AMOUNT_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(BILL_METHOD)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_BILL_METHOD
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(BILL_METHOD)) <> 0 THEN BILL_METHOD ELSE 0 END) AS TOTAL_BILL_METHOD_DISTINTOS
FROM STAGE.STG_FACTURAS_FCT;


# Visualización del contenido:
SELECT COUNT(*) AS TOTAL_REGITROS 
, SUM(CASE WHEN LENGTH(TRIM(BILL_CYCLE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_BILL_CYCLE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(BILL_CYCLE)) <> 0 THEN BILL_CYCLE ELSE 0 END) AS TOTAL_BILL_CYCLE_DISTINTOS
, BILL_CYCLE, LENGTH(BILL_CYCLE)
FROM STAGE.STG_FACTURAS_FCT
GROUP BY BILL_CYCLE
ORDER BY LENGTH(BILL_CYCLE) DESC;

SELECT COUNT(*) AS TOTAL_REGITROS 
, SUM(CASE WHEN LENGTH(TRIM(AMOUNT)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_AMOUNT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AMOUNT)) <> 0 THEN AMOUNT ELSE 0 END) AS TOTAL_AMOUNT_DISTINTOS
, AMOUNT
FROM STAGE.STG_FACTURAS_FCT
GROUP BY AMOUNT;

SELECT COUNT(*) AS TOTAL_REGITROS 
, SUM(CASE WHEN LENGTH(TRIM(BILL_METHOD)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_BILL_METHOD
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(BILL_METHOD)) <> 0 THEN BILL_METHOD ELSE 0 END) AS TOTAL_BILL_METHOD_DISTINTOS
, BILL_METHOD, LENGTH(BILL_METHOD)
FROM STAGE.STG_FACTURAS_FCT
GROUP BY BILL_METHOD
ORDER BY LENGTH(BILL_METHOD) DESC;
