USE STAGE;
SELECT COUNT(*) AS TOTAL_REGITROS 
, SUM(CASE WHEN LENGTH(TRIM(ID)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_ID
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(ID)) <> 0 THEN ID ELSE 0 END) AS TOTAL_ID_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(PHONE_NUMBER)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_PHONE_NUMBER
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PHONE_NUMBER)) <> 0 THEN PHONE_NUMBER ELSE 0 END) AS TOTAL_PHONE_NUMBER_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(START_DATETIME)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_START_DATETIME
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(START_DATETIME)) <> 0 THEN START_DATETIME ELSE 0 END) AS TOTAL_START_DATETIME_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(END_DATETIME)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_END_DATETIME
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(END_DATETIME)) <> 0 THEN END_DATETIME ELSE 0 END) AS TOTAL_END_DATETIME_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(SERVICE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_SERVICE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(SERVICE)) <> 0 THEN SERVICE ELSE 0 END) AS TOTAL_SERVICE_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(FLG_TRANSFER)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_FLG_TRANSFER
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(FLG_TRANSFER)) <> 0 THEN FLG_TRANSFER ELSE 0 END) AS TOTAL_FLG_TRANSFER_DISTINTOS
, SUM(CASE WHEN LENGTH(TRIM(AGENT)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_AGENT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AGENT)) <> 0 THEN AGENT ELSE 0 END) AS TOTAL_AGENT_DISTINTOS
FROM STAGE.STG_CONTACTOS_IVR;

# Visualización del contenido
SELECT COUNT(*) AS TOTAL_REGITROS 
, SUM(CASE WHEN LENGTH(TRIM(AGENT)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_AGENT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AGENT)) <> 0 THEN AGENT ELSE 0 END) AS TOTAL_AGENT_DISTINTOS
, AGENT	
, LENGTH(AGENT)
FROM STAGE.STG_CONTACTOS_IVR
GROUP BY AGENT
ORDER BY LENGTH(AGENT) DESC;

SELECT COUNT(*) AS TOTAL_REGITROS 
, SUM(CASE WHEN LENGTH(TRIM(FLG_TRANSFER)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_FLG_TRANSFER
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(FLG_TRANSFER)) <> 0 THEN FLG_TRANSFER ELSE 0 END) AS TOTAL_FLG_TRANSFER_DISTINTOS
, FLG_TRANSFER
FROM STAGE.STG_CONTACTOS_IVR
GROUP BY FLG_TRANSFER;

SELECT COUNT(*) AS TOTAL_REGITROS 
, SUM(CASE WHEN LENGTH(TRIM(SERVICE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_SERVICE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(SERVICE)) <> 0 THEN SERVICE ELSE 0 END) AS TOTAL_SERVICE_DISTINTOS
, SERVICE, LENGTH(SERVICE)
FROM STAGE.STG_CONTACTOS_IVR
GROUP BY SERVICE
ORDER BY LENGTH(SERVICE) DESC;
