# CREACIÓN DE TABLAS DEL MODELO DE FACTURAS
USE ODS;

#ALTER TABLE ODS_HC_CLIENTES DROP FOREIGN KEY fk_cl
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS ODS_HC_CLIENTES;

CREATE TABLE ODS_HC_CLIENTES
(ID_CLIENTE INT NOT NULL PRIMARY KEY
, NOMBRE_CLIENTE VARCHAR(512)
, APELLIDOS_CLIENTE VARCHAR(512)
, NUMDOC_CLIENTE VARCHAR(24)
, ID_SEXO INT
, ID_DIRECCION_CLIENTE INT
, TELEFONO_CLIENTE BIGINT
, EMAIL VARCHAR(512)
, FC_NACIMIENTO DATE
, ID_PROFESION INT
, ID_COMPANYA INT
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_HC_FACTURAS;

CREATE TABLE ODS_HC_FACTURAS 
(ID_FACTURA INT NOT NULL PRIMARY KEY
, ID_CLIENTE INT
, FC_INICIO DATETIME
, FC_FIN DATETIME
, FC_ESTADO DATETIME
, FC_PAGO DATETIME
, ID_CICLO_FACTURACION INT
, ID_METODO_PAGO INT
, CANTIDAD FLOAT(10,2)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_METODOS_PAGO;

CREATE TABLE ODS_DM_METODOS_PAGO
(ID_METODO_PAGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY
, DE_METODO_PAGO VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_CICLOS_FACTURACION;

CREATE TABLE ODS_DM_CICLOS_FACTURACION
(ID_CICLO_FACTURACION INT NOT NULL AUTO_INCREMENT PRIMARY KEY
, DE_CICLO_FACTURACION VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);


